title: <p align="center"> Gurukeerthana Gaddam </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/guru-keerthana-gaddam-649642109/">LinkedIn</a> |
  <a href="https://github.com/Keerthanagaddam">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
